export const GET_IMAGES = 'GET_IMAGES';
export const SET_LOADING = 'SET_LOADING';
export const SET_PAGINATION_LOADING = 'SET_PAGINATION_LOADING';
export const SET_FILTERED_IMAGES_LIST = 'SET_FILTERED_IMAGES_LIST';
export const SET_SINGLE_IMAGE_DETAILS_LOADING = 'SET_SINGLE_IMAGE_DETAILS_LOADING';
export const GET_SINGLE_IMAGE_DETAILS = 'GET_SINGLE_IMAGE_DETAILS';
export const SET_SINGLE_IMAGE_DETAILS_ERROR = 'SET_SINGLE_IMAGE_DETAILS_ERROR';
export const SET_IMAGES_ERROR = 'SET_IMAGES_ERROR';
